"""Black-box provenance ownership tests for the generated runtime brief.

Every test drives ``bin/ai-specs`` verbs (sync / sync-agent / init / doctor)
through the process boundary against an isolated install root. No test may
import ``lib/_internal`` modules. Assertions preserve the original contract
intents (preserved vs adopted vs regenerated bytes, lock baselines, remedy
needles) through CLI-observable surfaces: AGENTS.md bytes, the lock file's
[managed."AGENTS.md"] entry, and stdout/stderr needles.
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _blackbox import invoke, isolated_home  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
LOCK_NAME = "AGENTS.md"


def _make_home(base: Path) -> Path:
    """Isolated CLI install root with a REAL lib copy (see test_sync_pipeline)."""
    home = isolated_home(base)
    (home / "lib").unlink()
    shutil.copytree(
        ROOT / "lib", home / "lib", symlinks=True,
        ignore=shutil.ignore_patterns("_vendor", "__pycache__"),
    )
    return home


_HOMES: dict[str, Path] = {}


def _home_for(project: Path) -> Path:
    """One shared isolated install root per command sequence."""
    base = project.parent
    key = str(base)
    if key not in _HOMES:
        _HOMES[key] = _make_home(base)
    return _HOMES[key]


def _brief_sha(source: "Path | bytes") -> str:
    """sha256 of normalized bytes — the CLI's own baseline hash contract
    (CRLF/LF line endings are equivalent, mirroring the lock writer)."""
    data = source if isinstance(source, bytes) else Path(source).read_bytes()
    return hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def _drop_managed_baseline(lock_path: Path, name: str = LOCK_NAME) -> None:
    """Remove one [managed."name"] entry from a lock file, line-based.

    Mirrors the lock writer's format: the entry header line plus its
    following key = "value" lines, up to the next table header.
    """
    lines = lock_path.read_text().splitlines(keepends=True)
    out: list[str] = []
    skipping = False
    for line in lines:
        if line.strip() == f'[managed."{name}"]':
            skipping = True
            continue
        if skipping:
            if line.startswith("["):
                skipping = False
            else:
                continue
        out.append(line)
    lock_path.write_text("".join(out))


def _corrupt_managed_sha(lock_path: Path, name: str = LOCK_NAME) -> None:
    """Poison one managed entry's sha256 to 64 zeros (interrupted-write crash)."""
    lines = lock_path.read_text().splitlines(keepends=True)
    in_span = False
    for i, line in enumerate(lines):
        if line.strip() == f'[managed."{name}"]':
            in_span = True
            continue
        if in_span:
            if line.startswith("["):
                break
            if line.startswith("sha256"):
                lines[i] = f'sha256 = "{"0" * 64}"\n'
                break
    lock_path.write_text("".join(lines))


def _lock_managed(lock_path: Path) -> dict:
    return tomllib.loads(lock_path.read_text()).get("managed", {})


class RuntimeBriefOwnershipTests(unittest.TestCase):
    def _stage(self, name: str = "demo") -> tuple[Path, Path, Path]:
        """Minimal project: ai-specs/ manifest (+ skills/commands dirs)."""
        td = tempfile.TemporaryDirectory(prefix="ai-specs-own-")
        self.addCleanup(td.cleanup)
        project = Path(td.name) / "project"
        (project / "ai-specs" / "skills").mkdir(parents=True)
        (project / "ai-specs" / "commands").mkdir()
        toml = project / "ai-specs" / "ai-specs.toml"
        toml.write_text(f"[project]\nname = '{name}'\n")
        return project, toml, project / "AGENTS.md"

    def _sync(self, project: Path, *extra: str):
        return invoke(project, "sync", *extra, cli_home=_home_for(project))

    # -- classification states through the sync verb ------------------------

    def test_untracked_brief_is_preserved_with_both_remedies(self):
        project, _toml, output = self._stage()
        original = b"# hand-written instructions\n"
        output.write_bytes(original)
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), original)
        message = result.stderr
        self.assertIn("untracked", message)
        self.assertIn("--adopt-brief", message)
        self.assertIn("ai-specs:runtime-brief", message)

    def test_missing_brief_is_written_and_baseline_recorded(self):
        project, _toml, output = self._stage()
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(output.is_file())
        lock = _lock_managed(project / "ai-specs/.ai-specs.lock")
        entry = lock[LOCK_NAME]
        self.assertEqual(entry["kind"], "runtime-brief")
        self.assertEqual(entry["policy"], "never-force")
        self.assertEqual(entry["sha256"], _brief_sha(output))

    def test_user_modified_brief_is_preserved(self):
        project, toml, output = self._stage()
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        original = output.read_bytes()
        output.write_bytes(original + b"\n# local context\n")
        edited = output.read_bytes()
        toml.write_text("[project]\nname = 'changed'\n")
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), edited)
        self.assertIn("user_modified", result.stderr)

    def test_managed_stale_brief_updates_and_records_new_baseline(self):
        project, toml, output = self._stage()
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        old = output.read_bytes()
        toml.write_text("[project]\nname = 'changed'\n")
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertNotEqual(output.read_bytes(), old)
        self.assertIn("# changed Runtime Brief", output.read_text())
        combined = result.stdout + result.stderr
        self.assertNotIn(
            "AGENTS.md left unchanged", combined,
            "a stale managed brief must be refreshed, not preserved",
        )
        lock = _lock_managed(project / "ai-specs/.ai-specs.lock")
        self.assertEqual(lock[LOCK_NAME]["sha256"], _brief_sha(output))

    def test_exact_match_without_baseline_adopts_silently(self):
        project, _toml, output = self._stage()
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        expected = output.read_bytes()
        # Drop the recorded baseline: the bytes on disk are exactly what the
        # CLI would write, so the next sync must adopt them silently.
        _drop_managed_baseline(project / "ai-specs/.ai-specs.lock")
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), expected)
        combined = result.stdout + result.stderr
        self.assertNotIn(
            "AGENTS.md left unchanged", combined,
            "an exact match without baseline must adopt silently",
        )
        self.assertEqual(
            _lock_managed(project / "ai-specs/.ai-specs.lock")[LOCK_NAME]["sha256"],
            _brief_sha(output),
        )

    def test_divergent_brief_without_baseline_is_preserved_without_adoption(self):
        project, _toml, output = self._stage()
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        _drop_managed_baseline(project / "ai-specs/.ai-specs.lock")
        original = b"# stale generated-looking text\n"
        output.write_bytes(original)
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), original)
        self.assertNotIn(
            LOCK_NAME, _lock_managed(project / "ai-specs/.ai-specs.lock"),
            "a divergent untracked brief must not be adopted into the lock",
        )
        self.assertIn("untracked", result.stderr)

    def test_explicit_adoption_records_current_bytes(self):
        project, _toml, output = self._stage()
        original = b"# intentionally adopted brief\n"
        output.write_bytes(original)
        result = self._sync(project, "--adopt-brief")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), original)
        self.assertEqual(
            _lock_managed(project / "ai-specs/.ai-specs.lock")[LOCK_NAME]["sha256"],
            _brief_sha(original),
        )

    def test_marker_is_unconditional_even_without_legacy_flag(self):
        project, _toml, output = self._stage()
        original = b"# mine\n<!-- ai-specs:runtime-brief -->\n"
        output.write_bytes(original)
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), original)

    def test_managed_current_is_a_silent_noop(self):
        project, _toml, output = self._stage()
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        before_lock = (project / "ai-specs/.ai-specs.lock").read_bytes()
        before_brief = output.read_bytes()
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), before_brief)
        combined = result.stdout + result.stderr
        self.assertNotIn(
            "AGENTS.md left unchanged", combined,
            "a current managed brief must be a silent noop",
        )
        self.assertEqual(
            (project / "ai-specs/.ai-specs.lock").read_bytes(), before_lock,
            "a noop sync must not touch the lock",
        )

    # -- fan-out, doctor, init, and recovery surfaces -----------------------

    def test_sync_agent_fanout_uses_same_preservation_decision(self):
        project, toml, output = self._stage()
        (project / "packages" / "a" / "ai-specs").mkdir(parents=True)
        output.write_bytes(b"# root instructions\n")
        child = project / "packages" / "a" / "AGENTS.md"
        child.write_bytes(b"# child instructions\n")
        toml.write_text(
            "[project]\nname = 'demo'\nsubrepos = ['packages/a']\n\n"
            "[agents]\nenabled = ['claude']\n"
        )
        result = invoke(project, "sync-agent", "--all", cli_home=_home_for(project))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(child.read_bytes(), b"# child instructions\n")
        combined = result.stdout + result.stderr
        self.assertIn("--adopt-brief", combined)
        self.assertIn("ai-specs:runtime-brief", combined)

    def test_doctor_reports_untracked_brief_with_both_remedies(self):
        project, _toml, output = self._stage()
        output.write_bytes(b"# hand-written instructions\n")
        result = invoke(project, "doctor", cli_home=_home_for(project))
        combined = result.stdout + result.stderr
        provenance_lines = [l for l in combined.splitlines() if "brief-provenance" in l]
        self.assertEqual(
            len(provenance_lines), 1,
            f"exactly one brief-provenance check expected, got: {provenance_lines}",
        )
        self.assertIn("untracked", combined)
        self.assertIn("--adopt-brief", combined)
        self.assertIn("runtime-brief", combined)

    def test_init_preserves_pre_existing_brief_without_marker(self):
        td = tempfile.TemporaryDirectory(prefix="ai-specs-own-init-")
        self.addCleanup(td.cleanup)
        project = Path(td.name) / "project"
        project.mkdir()
        original = b"# written before ai-specs\n"
        (project / "AGENTS.md").write_bytes(original)
        result = invoke(project, "init", cli_home=_home_for(project))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual((project / "AGENTS.md").read_bytes(), original)
        self.assertIn("--adopt-brief", result.stdout + result.stderr)

    def test_explicit_adoption_via_sync_cli_records_untracked_brief(self):
        td = tempfile.TemporaryDirectory(prefix="ai-specs-own-adopt-")
        self.addCleanup(td.cleanup)
        project = Path(td.name) / "project"
        project.mkdir()
        original = b"# written before ai-specs\n"
        (project / "AGENTS.md").write_bytes(original)
        home = _home_for(project)
        result = invoke(project, "init", cli_home=home)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        lock_path = project / "ai-specs/.ai-specs.lock"
        self.assertNotIn(LOCK_NAME, _lock_managed(lock_path))
        result = invoke(project, "sync", "--adopt-brief", cli_home=home)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual((project / "AGENTS.md").read_bytes(), original)
        self.assertIn(LOCK_NAME, _lock_managed(lock_path))

    def test_lock_with_corrupt_baseline_entry_preserves_divergent_brief(self):
        """A semantically broken lock entry must fail closed to preservation.

        The managed entry carries a non-string sha256 (valid TOML, garbage
        integrity data): the classifier treats it as no baseline and preserves
        the divergent brief with the standard remedy message.
        """
        project, _toml, output = self._stage()
        home = _home_for(project)
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        edited = output.read_bytes() + b"\n# divergent\n"
        output.write_bytes(edited)
        (project / "ai-specs/.ai-specs.lock").write_text(
            f'[managed."{LOCK_NAME}"]\n'
            "sha256 = 123\n"
            'kind = "runtime-brief"\n'
            'policy = "never-force"\n'
        )
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), edited)
        self.assertIn("preserv", (result.stdout + result.stderr).lower())

    def test_unreadable_target_preserves_without_traceback(self):
        project, _toml, output = self._stage()
        original = b"# keep this\n"
        output.write_bytes(original)
        output.chmod(0o000)
        self.addCleanup(lambda: output.chmod(0o644))
        result = self._sync(project)
        output.chmod(0o644)  # restore access before asserting on the bytes
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(output.read_bytes(), original)
        self.assertIn("undetermined", result.stderr)
        combined = result.stdout + result.stderr
        self.assertNotIn("Traceback", combined)


class BriefRecoveryTests(RuntimeBriefOwnershipTests):
    """Judgment-day round one: the documented remedy must actually work."""

    def test_adopt_brief_works_for_user_modified(self):
        """JD C1 (both judges): the preserve message, doctor guidance and the
        troubleshooting doc all tell the user to run `ai-specs sync
        --adopt-brief`. The user_modified branch never inspected the flag, so
        the documented remedy silently did nothing — forever.

        Design D3 forbids AUTOMATIC updates of user_modified. It does not
        forbid an explicit user-issued handoff; D6 says --adopt-brief is safe
        precisely because the user issues it.
        """
        project, _toml, output = self._stage()
        home = _home_for(project)
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        edited = output.read_bytes() + b"\nmy own section\n"
        output.write_bytes(edited)

        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn(
            "AGENTS.md left unchanged", result.stdout + result.stderr,
            "fixture precondition: the divergent brief must be preserved first",
        )

        result = self._sync(project, "--adopt-brief")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(
            output.read_bytes(), edited,
            "adoption must keep the user's bytes, never overwrite them",
        )
        lock = _lock_managed(project / "ai-specs/.ai-specs.lock")
        self.assertEqual(lock[LOCK_NAME]["sha256"], _brief_sha(output))

    def test_interrupted_write_self_heals(self):
        """JD (judge B): write_bytes runs before set_brief_baseline. A crash
        between them leaves disk ahead of the lock, so the next sync classifies
        an ordinary never-edited brief as user_modified and preserves it
        forever — with no working recovery, since --adopt-brief was dead for
        that state.

        Content byte-identical to what we would write is provably ours, so
        re-recording the baseline is safe: it can never adopt foreign content.
        """
        project, _toml, output = self._stage()
        home = _home_for(project)
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        lock_path = project / "ai-specs/.ai-specs.lock"
        _corrupt_managed_sha(lock_path)

        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        combined = result.stdout + result.stderr
        self.assertNotIn(
            "AGENTS.md left unchanged", combined,
            "an unmodified brief stayed stuck after an interrupted write: " + combined,
        )
        self.assertEqual(
            _lock_managed(lock_path)[LOCK_NAME]["sha256"], _brief_sha(output),
            "the interrupted-write baseline must be re-recorded (self-heal)",
        )

    def test_adopt_gate_agrees_with_the_classifier_on_line_endings(self):
        """JD (judge A): the classifier normalizes CRLF before hashing, the
        adopt gate compared raw bytes. A CRLF checkout of our own output was
        therefore called divergent and preserved — hitting exactly the
        no-regression cohort the migration rule exists to protect.
        """
        project, _toml, output = self._stage()
        home = _home_for(project)
        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        rendered = output.read_bytes()
        lock_path = project / "ai-specs/.ai-specs.lock"
        _drop_managed_baseline(lock_path)          # no baseline: first sight
        output.write_bytes(rendered.replace(b"\n", b"\r\n"))

        result = self._sync(project)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        combined = result.stdout + result.stderr
        self.assertNotIn(
            "AGENTS.md left unchanged", combined,
            "a CRLF checkout of our own output was not adopted: " + combined,
        )
        self.assertIn(LOCK_NAME, _lock_managed(lock_path))


if __name__ == "__main__":
    unittest.main()
