"""Tests for hooks-render.py — per-harness runtime-hook wiring.

See openspec/changes/recipe-runtime-hooks/specs/runtime-hook-distribution/spec.md.
"""
from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HOOKS_RENDER_PATH = ROOT / "lib" / "_internal" / "hooks-render.py"


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


SHELL_HOOK = {
    "recipe": "demo",
    "id": "shell-gate",
    "event": "pre-tool-use",
    "matcher": "Bash",
    "blocking": True,
    "script_path": "ai-specs/recipes/demo/hooks/gate.sh",
    "env": {"DEMO_VAR": "v1"},
}

FILEWRITE_HOOK = {
    "recipe": "worktree-flow",
    "id": "worktree-gate",
    "event": "pre-tool-use",
    "matcher": "Edit|Write|MultiEdit|NotebookEdit",
    "blocking": True,
    "script_path": "ai-specs/recipes/worktree-flow/hooks/worktree-gate.sh",
    "env": {"WORKTREE_GATE_PROTECTED": "main development"},
}


class HooksRenderTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.mod = load_module(HOOKS_RENDER_PATH, "hooks_render_internal")

    def _project(self) -> Path:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        return Path(tmp.name)

    def _write_resolved(self, project: Path, agents, hooks) -> Path:
        p = project / "resolved-hooks.json"
        p.write_text(json.dumps({"enabled_agents": agents, "hooks": hooks}))
        return p

    def test_claude_pretooluse_managed_block(self):
        project = self._project()
        resolved = self._write_resolved(project, ["claude"], [SHELL_HOOK])
        self.mod.render(resolved, "claude", project)
        settings = json.loads((project / ".claude" / "settings.json").read_text())
        pre = settings["hooks"]["PreToolUse"]
        # Find the managed entry for this hook
        entry = next(e for e in pre if e.get("matcher") == "Bash")
        cmd = entry["hooks"][0]["command"]
        self.assertIn("ai-specs/recipes/demo/hooks/gate.sh", cmd)
        self.assertEqual(entry["hooks"][0]["type"], "command")

    def test_cursor_hooks_json(self):
        project = self._project()
        # Use a Bash-matcher hook so Cursor has a real target (beforeShellExecution)
        resolved = self._write_resolved(project, ["cursor"], [SHELL_HOOK])
        self.mod.render(resolved, "cursor", project)
        wrapper = project / ".cursor" / "hooks" / "demo-shell-gate.sh"
        self.assertTrue(wrapper.is_file(), "cursor wrapper should be generated")
        wtext = wrapper.read_text()
        self.assertIn("GENERATED by ai-specs", wtext)
        self.assertIn('"permission":"deny"', wtext.replace(" ", ""))
        hooks_json = json.loads((project / ".cursor" / "hooks.json").read_text())
        self.assertIn("beforeShellExecution", json.dumps(hooks_json))

    def test_opencode_plugin_shim(self):
        project = self._project()
        resolved = self._write_resolved(project, ["opencode"], [SHELL_HOOK])
        self.mod.render(resolved, "opencode", project)
        plugin = project / ".opencode" / "plugin" / "demo-shell-gate.ts"
        self.assertTrue(plugin.is_file(), "opencode plugin should be generated")
        text = plugin.read_text()
        self.assertIn("// GENERATED by ai-specs", text)
        self.assertIn("tool.execute.before", text)
        self.assertIn("throw", text)
        self.assertIn("ai-specs/recipes/demo/hooks/gate.sh", text)

    def test_pi_extension_shim(self):
        project = self._project()
        resolved = self._write_resolved(project, ["pi"], [SHELL_HOOK])
        self.mod.render(resolved, "pi", project)
        ext = project / ".pi" / "extensions" / "demo-shell-gate.ts"
        self.assertTrue(ext.is_file(), "pi extension should be generated")
        text = ext.read_text()
        self.assertIn("// GENERATED by ai-specs", text)
        self.assertIn("@earendil-works/pi-coding-agent", text)
        self.assertIn("ExtensionAPI", text)
        self.assertIn('pi.on("tool_call"', text)
        self.assertIn("block: true", text)
        # Pi exposes the tool name as camelCase `toolName` (verified June 2026);
        # reading only snake_case would make the matcher never fire. Lock it in.
        self.assertIn("call?.toolName", text)

    def test_unsupported_event_warns_and_skips(self):
        project = self._project()
        # `stop` has no opencode mapping -> warn + skip for opencode, present for claude
        stop_hook = dict(SHELL_HOOK, id="stopper", event="stop", matcher="")
        resolved = self._write_resolved(project, ["opencode", "claude"], [stop_hook])
        warnings_oc = self.mod.render(resolved, "opencode", project)
        # No plugin file emitted for opencode
        self.assertFalse((project / ".opencode" / "plugin" / "demo-stopper.ts").exists())
        joined = " ".join(warnings_oc)
        self.assertIn("demo", joined)
        self.assertIn("stopper", joined)
        self.assertIn("stop", joined)
        self.assertIn("opencode", joined)
        # claude supports stop
        self.mod.render(resolved, "claude", project)
        settings = json.loads((project / ".claude" / "settings.json").read_text())
        self.assertIn("Stop", settings["hooks"])

    def test_cursor_no_prefilewrite_target_warns_and_skips(self):
        project = self._project()
        resolved = self._write_resolved(project, ["cursor"], [FILEWRITE_HOOK])
        warnings = self.mod.render(resolved, "cursor", project)
        wrapper = project / ".cursor" / "hooks" / "worktree-flow-worktree-gate.sh"
        self.assertFalse(wrapper.exists(), "cursor must skip file-write gates")
        joined = " ".join(warnings).lower()
        self.assertIn("cursor", joined)
        self.assertIn("worktree-gate", " ".join(warnings))

    def test_render_idempotent(self):
        project = self._project()
        resolved = self._write_resolved(project, ["claude"], [SHELL_HOOK])
        self.mod.render(resolved, "claude", project)
        first = (project / ".claude" / "settings.json").read_bytes()
        self.mod.render(resolved, "claude", project)
        second = (project / ".claude" / "settings.json").read_bytes()
        self.assertEqual(first, second, "second render must be byte-identical")

    def test_user_hook_preserved(self):
        project = self._project()
        claude_dir = project / ".claude"
        claude_dir.mkdir(parents=True)
        (claude_dir / "settings.json").write_text(json.dumps({
            "model": "opus",
            "hooks": {
                "PreToolUse": [
                    {"matcher": "UserOwned", "hooks": [
                        {"type": "command", "command": "/usr/bin/true"}
                    ]}
                ]
            }
        }, indent=2))
        resolved = self._write_resolved(project, ["claude"], [SHELL_HOOK])
        self.mod.render(resolved, "claude", project)
        settings = json.loads((claude_dir / "settings.json").read_text())
        # Sibling user key preserved
        self.assertEqual(settings["model"], "opus")
        matchers = [e.get("matcher") for e in settings["hooks"]["PreToolUse"]]
        self.assertIn("UserOwned", matchers)  # user hook preserved
        self.assertIn("Bash", matchers)       # managed hook added


if __name__ == "__main__":
    unittest.main()
