#!/usr/bin/env python3
"""Render <project>/AGENTS.md from ai-specs.toml + skills/ + agents.d/.

Inputs:
  - ai-specs.toml         → [project].name (and optional [project].description)
  - ai-specs/skills/*/SKILL.md frontmatter → skills index table
  - ai-specs/agents.d/*.md (sorted, lexicographic) → user content fragments

Output (to <output_path>, typically <project>/AGENTS.md):
  # {name} — Agent Instructions
  > Auto-generated by `specs-ai sync`.

  {agents.d fragments concatenated}

  ## Skills
  | Skill | Description | Link |
  | --- | --- | --- |
  | … one row per SKILL.md … |

  > [SKILL.md](ai-specs/skills/<first>/SKILL.md)   ← skill-sync insert anchor

  ### Auto-invoke Skills
  (placeholder — replaced on next `skill-sync` run)

  | Action | Skill |
  | --- | --- |

  ## How AI tooling is wired
  (boilerplate explaining the standard)

Usage:
  agents-md-render.py <project_root> <output_path>
"""

import re
import sys
import tomllib
from pathlib import Path


HEADER_BANNER = """\
> **Auto-generated by `specs-ai sync`.** Edit user content under \
[`ai-specs/agents.d/`](ai-specs/agents.d/). The `Skills` index and the \
`Auto-invoke Skills` table below are derived from \
[`ai-specs/skills/`](ai-specs/skills/) — do not hand-edit.
"""


FOOTER = """\
## How AI tooling is wired

This project uses the **`ai-specs`** standard, driven by the global
[`specs-ai`](https://github.com/nnodes/specs-ai-cli) CLI. The manifest at
[`ai-specs/ai-specs.toml`](ai-specs/ai-specs.toml) declares enabled agents,
vendored skills, and MCP servers. Per-agent configs (`.claude/`, `.cursor/`,
`opencode.json`, …) are generated from the manifest — do not hand-edit; they're
gitignored.

Common commands (run from project root):

```bash
specs-ai sync                  # vendor deps + regenerate AGENTS.md + fan out per agent
specs-ai add-skill <name>      # local skill (lives in this repo)
specs-ai add-dep <git-url>     # vendored skill (external, gitignored)
specs-ai sync-agent --claude   # re-render configs for a single agent
```

Inside a configured agent, run **`/skills-as-rules`** to bootstrap project
skills from existing AI rules / conventions / docs.
"""


def parse_skill(path: Path) -> dict:
    """Extract {name, description} from a SKILL.md YAML frontmatter.

    Hand-rolled — we avoid a YAML dep. Handles:
      - inline description:   `description: text`
      - block scalar:         `description: >` followed by indented lines
    """
    text = path.read_text()
    if not text.startswith("---"):
        return {}

    # Frontmatter is between the first two `---` lines.
    body = text[3:]  # drop leading ---
    end = body.find("\n---")
    if end < 0:
        return {}
    fm_lines = body[:end].splitlines()
    # Drop the leading newline from the split, normalize.
    fm_lines = [ln for ln in fm_lines]

    name = ""
    description = ""

    i = 0
    while i < len(fm_lines):
        line = fm_lines[i]
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", line)
        if not m:
            i += 1
            continue
        key, rest = m.group(1), m.group(2).strip()

        if key == "name":
            name = rest.strip().strip('"').strip("'")

        elif key == "description":
            if rest and rest not in (">", "|", ">-", "|-"):
                description = rest
            else:
                # Block scalar — collect indented continuation lines.
                buf = []
                j = i + 1
                while j < len(fm_lines):
                    nxt = fm_lines[j]
                    if not nxt.strip():
                        buf.append("")
                        j += 1
                        continue
                    # Top-level key terminates the block.
                    if re.match(r"^[A-Za-z_][A-Za-z0-9_-]*:", nxt):
                        break
                    buf.append(nxt.strip())
                    j += 1
                description = " ".join(b for b in buf if b)

        i += 1

    # Trim description to first useful sentence; drop the "Trigger: …" tail.
    if "Trigger:" in description:
        description = description.split("Trigger:")[0].rstrip(". ")
    description = description.strip().rstrip(".")

    return {"name": name, "description": description}


def collect_skills(skills_dir: Path) -> list[dict]:
    """Return [{name, description, rel_link}] for every immediate subdir
    of `skills_dir` that contains a SKILL.md."""
    rows = []
    if not skills_dir.is_dir():
        return rows
    for child in sorted(skills_dir.iterdir()):
        if not child.is_dir():
            continue
        skill_md = child / "SKILL.md"
        if not skill_md.is_file():
            continue
        info = parse_skill(skill_md)
        if not info.get("name"):
            info["name"] = child.name
        if not info.get("description"):
            info["description"] = "(no description)"
        info["rel_link"] = f"ai-specs/skills/{child.name}/SKILL.md"
        rows.append(info)
    return rows


def render_skills_index(skills: list[dict]) -> str:
    if not skills:
        return (
            "## Skills\n\n"
            "_No skills yet._ Run `specs-ai add-skill <name>` to scaffold one,\n"
            "or `specs-ai add-dep <git-url>` to vendor an external skill.\n"
        )

    out = ["## Skills", ""]
    out.append("All skills live in [`ai-specs/skills/`](ai-specs/skills/). "
               "Load explicitly with `Read ai-specs/skills/<name>/SKILL.md`.")
    out.append("")
    out.append("| Skill | Description | Link |")
    out.append("|-------|-------------|------|")
    for s in skills:
        # Escape pipes inside description for table safety.
        desc = s["description"].replace("|", "\\|")
        out.append(f"| `{s['name']}` | {desc} | [SKILL.md]({s['rel_link']}) |")
    out.append("")

    # Bootstrap insert-anchor for skill-sync's first run on a new repo:
    # skill-sync inserts the auto-invoke table AFTER a `> ... SKILL.md)` blockquote.
    first = skills[0]
    out.append(f"> [SKILL.md]({first['rel_link']})")
    out.append("")
    return "\n".join(out)


def render_auto_invoke_placeholder() -> str:
    return (
        "### Auto-invoke Skills\n\n"
        "(Regenerated by `skill-sync`. Do not edit by hand.)\n\n"
        "When performing these actions, ALWAYS invoke the corresponding skill FIRST:\n\n"
        "| Action | Skill |\n"
        "|--------|-------|\n"
    )


def collect_agents_d(agents_d: Path) -> str:
    """Concatenate every *.md fragment in agents.d/, alphabetically sorted.
    Skip files starting with `_` (drafts) and `README.md` (instructions to user)."""
    if not agents_d.is_dir():
        return ""
    chunks = []
    for f in sorted(agents_d.iterdir()):
        if not f.is_file() or f.suffix != ".md":
            continue
        if f.name.startswith("_") or f.name.lower() == "readme.md":
            continue
        body = f.read_text().rstrip()
        if body:
            chunks.append(body)
    return "\n\n".join(chunks)


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "Usage: agents-md-render.py <project_root> <output_path>",
            file=sys.stderr,
        )
        return 2

    project_root = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    toml_path = project_root / "ai-specs" / "ai-specs.toml"
    skills_dir = project_root / "ai-specs" / "skills"
    agents_d = project_root / "ai-specs" / "agents.d"

    if not toml_path.is_file():
        print(f"error: {toml_path} not found", file=sys.stderr)
        return 1

    with toml_path.open("rb") as f:
        data = tomllib.load(f)
    project = data.get("project", {}) or {}
    name = project.get("name") or project_root.name

    skills = collect_skills(skills_dir)
    user_content = collect_agents_d(agents_d)

    parts = [
        f"# {name} — Agent Instructions",
        "",
        HEADER_BANNER.rstrip(),
        "",
    ]
    if user_content:
        parts.append(user_content)
        parts.append("")
    parts.append(render_skills_index(skills))
    parts.append(render_auto_invoke_placeholder())
    parts.append("")
    parts.append(FOOTER.rstrip())
    parts.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(parts))
    print(f"  ✓ wrote {output_path} ({len(skills)} skill(s), agents.d: "
          f"{'yes' if user_content else 'empty'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
