#!/usr/bin/env python3
"""Render AGENTS.md from a root manifest plus a target-local skills tree.

Usage:
  agents-md-render.py <manifest_root> <output_path> [--skills-dir <path>]

By default, skills are read from <manifest_root>/ai-specs/skills. For subrepo
fan-out, pass --skills-dir <target>/ai-specs/skills so links stay local while
project metadata still comes from the root manifest.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path


HEADER_BANNER = """\
> **Auto-generated by `ai-specs sync`.** Source of truth: \
[`ai-specs/`](ai-specs/). To formalize a new convention (commits, \
architecture, testing, …) as a skill, run **`/skills-as-rules`** inside \
your agent — it will guide you and call `skill-creator` + `skill-sync` \
under the hood.
"""


FOOTER = """\
## How AI tooling is wired

This project uses the **`ai-specs`** standard, driven by the global
[`ai-specs`](https://github.com/parada1104/ai-specs-cli) CLI. The manifest at
[`ai-specs/ai-specs.toml`](ai-specs/ai-specs.toml) declares enabled agents,
vendored skills, and MCP servers. Per-agent configs (`.claude/`, `.cursor/`,
`opencode.json`, …) are generated from the manifest — do not hand-edit; they're
gitignored.

Common commands (run from project root):

```bash
ai-specs sync                  # vendor deps + regenerate AGENTS.md + fan out per target + per agent
ai-specs add-dep <git-url>     # vendored skill (external, gitignored)
ai-specs sync-agent --claude   # re-render configs for the current target from the root manifest
```

Inside a configured agent, run **`/skills-as-rules`** whenever you want to
formalize a convention as a local skill — the command is interactive and walks
you through one skill at a time using `skill-creator` + `skill-sync`.

> Subrepo note: local `ai-specs/` contents are derived artifacts from the root
> sync run in multi-target mode. Treat them as generated outputs, not editable
> manifest sources.
"""


CONTEXT_PRECEDENCE_ORDER = (
    "canonical docs > project skills > packs > handoffs > session memory > "
    "proposed context"
)


def parse_skill(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---"):
        return {}

    body = text[3:]
    end = body.find("\n---")
    if end < 0:
        return {}
    fm_lines = body[:end].splitlines()

    name = ""
    description = ""

    i = 0
    while i < len(fm_lines):
        line = fm_lines[i]
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", line)
        if not m:
            i += 1
            continue
        key, rest = m.group(1), m.group(2).strip()

        if key == "name":
            name = rest.strip().strip('"').strip("'")
        elif key == "description":
            if rest and rest not in (">", "|", ">-", "|-"):
                description = rest
            else:
                buf = []
                j = i + 1
                while j < len(fm_lines):
                    nxt = fm_lines[j]
                    if not nxt.strip():
                        buf.append("")
                        j += 1
                        continue
                    if re.match(r"^[A-Za-z_][A-Za-z0-9_-]*:", nxt):
                        break
                    buf.append(nxt.strip())
                    j += 1
                description = " ".join(b for b in buf if b)

        i += 1

    if "Trigger:" in description:
        description = description.split("Trigger:")[0].rstrip(". ")
    description = description.strip().rstrip(".")

    return {"name": name, "description": description}


def collect_skills(skills_dir: Path) -> list[dict]:
    rows = []
    if not skills_dir.is_dir():
        return rows
    for child in sorted(skills_dir.iterdir()):
        if not child.is_dir():
            continue
        skill_md = child / "SKILL.md"
        if not skill_md.is_file():
            continue
        info = parse_skill(skill_md)
        if not info.get("name"):
            info["name"] = child.name
        if not info.get("description"):
            info["description"] = "(no description)"
        info["rel_link"] = f"ai-specs/skills/{child.name}/SKILL.md"
        rows.append(info)
    return rows


def render_skills_index(skills: list[dict]) -> str:
    if not skills:
        return (
            "## Skills\n\n"
            "_No skills yet._ Run `/skills-as-rules` inside your agent to create one,\n"
            "or `ai-specs add-dep <git-url>` to vendor an external skill.\n"
        )

    out = ["## Skills", ""]
    out.append("All skills live in [`ai-specs/skills/`](ai-specs/skills/). "
               "Load explicitly with `Read ai-specs/skills/<name>/SKILL.md`.")
    out.append("")
    out.append("| Skill | Description | Link |")
    out.append("|-------|-------------|------|")
    for s in skills:
        desc = s["description"].replace("|", "\\|")
        out.append(f"| `{s['name']}` | {desc} | [SKILL.md]({s['rel_link']}) |")
    out.append("")

    first = skills[0]
    out.append(f"> [SKILL.md]({first['rel_link']})")
    out.append("")
    return "\n".join(out)


def render_auto_invoke_placeholder() -> str:
    return (
        "### Auto-invoke Skills\n\n"
        "(Regenerated by `skill-sync`. Do not edit by hand.)\n\n"
        "When performing these actions, ALWAYS invoke the corresponding skill FIRST:\n\n"
        "| Action | Skill |\n"
        "|--------|-------|\n"
    )


def render_context_precedence(manifest_root: Path) -> str:
    doc_path = manifest_root / "docs" / "ai" / "context-precedence.md"
    if not doc_path.is_file():
        return ""

    return (
        "## Context Precedence\n\n"
        "When project context sources conflict, use this MVP order:\n\n"
        f"`{CONTEXT_PRECEDENCE_ORDER}`\n\n"
        "Canonical rule: "
        "[`docs/ai/context-precedence.md`](docs/ai/context-precedence.md). "
        "Treat it as an auditable decision policy, not an automatic merge engine.\n"
    )


def parse_args(argv: list[str]) -> tuple[Path, Path, Path]:
    if len(argv) < 3:
        raise ValueError("Usage: agents-md-render.py <manifest_root> <output_path> [--skills-dir <path>]")

    manifest_root = Path(argv[1])
    output_path = Path(argv[2])
    skills_dir = manifest_root / "ai-specs" / "skills"

    i = 3
    while i < len(argv):
        if argv[i] == "--skills-dir":
            skills_dir = Path(argv[i + 1])
            i += 2
            continue
        raise ValueError(f"unknown argument: {argv[i]}")

    return manifest_root, output_path, skills_dir


def main() -> int:
    try:
        manifest_root, output_path, skills_dir = parse_args(sys.argv)
    except (ValueError, IndexError) as exc:
        print(str(exc), file=sys.stderr)
        return 2

    toml_path = manifest_root / "ai-specs" / "ai-specs.toml"
    if not toml_path.is_file():
        print(f"error: {toml_path} not found", file=sys.stderr)
        return 1

    with toml_path.open("rb") as f:
        data = tomllib.load(f)
    project = data.get("project", {}) or {}
    name = project.get("name") or manifest_root.name

    skills = collect_skills(skills_dir)

    parts = [
        f"# {name} — Agent Instructions",
        "",
        HEADER_BANNER.rstrip(),
        "",
        render_skills_index(skills),
        render_context_precedence(manifest_root),
        render_auto_invoke_placeholder(),
        "",
        FOOTER.rstrip(),
        "",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(parts))
    print(f"  ✓ wrote {output_path} ({len(skills)} skill(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
