#!/usr/bin/env python3
"""Generate ai-specs/skills/vendor.manifest.toml from [[deps]] in ai-specs.toml.

vendor-skills.sh expects a vendor.manifest.toml with [[skills]] entries.
This script translates [[deps]] → [[skills]] keeping field names compatible.

Usage:
  deps-render.py <ai_specs_toml> <output_manifest_toml>
"""

import sys
import tomllib
from pathlib import Path


def serialize_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        # TOML basic string — escape backslash and double-quote
        escaped = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(v, list):
        return "[" + ", ".join(serialize_value(x) for x in v) + "]"
    raise TypeError(f"unsupported type for {v!r}: {type(v).__name__}")


HEADER = """# AUTOGENERATED from ai-specs/ai-specs.toml — do not edit by hand.
# Regenerate with: ai-specs init  (or ai-specs add-dep <url>)
#
# Consumed by ai-specs/skills/skill-sync/assets/vendor-skills.sh
"""


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <ai_specs_toml> <output_manifest_toml>", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])

    with src.open("rb") as f:
        data = tomllib.load(f)

    deps = data.get("deps", [])

    lines = [HEADER]
    for dep in deps:
        lines.append("[[skills]]")
        for key in (
            "id",
            "source",
            "scope_at_monorepo_root",
            "auto_invoke_root",
            "auto_invoke_subrepo",
            "install_into_subrepos",
            "only_subrepos",
            "license",
            "vendor_attribution",
        ):
            if key in dep:
                lines.append(f"{key} = {serialize_value(dep[key])}")
        lines.append("")

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines).rstrip() + "\n")
    print(f"  ✓ {dst} ({len(deps)} dep(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
