#!/usr/bin/env python3
"""Render <project>/ai-specs/.gitignore from ai-specs.toml.

Patterns derived:
  - Vendored deps (each [[deps]].id → skills/<id>/)
  - Generated artifacts (skills/vendor.manifest.toml)

Bundled skills (skill-creator, skill-sync) are NOT ignored — they are
committed by the project after `specs-ai init` so the project can customize
the skill template / sync behavior.

Usage:
  gitignore-render.py <toml_path> <output_path>
"""

import sys
import tomllib
from pathlib import Path


HEADER = """\
# --- specs-ai: managed by `specs-ai init`/`sync` — do not edit ---
"""

FOOTER = """\
# --- end specs-ai ---
"""


def render(deps: list[dict]) -> str:
    lines = [HEADER]
    if deps:
        lines.append("\n# Vendored skill deps (restored via `specs-ai sync`)")
        for d in deps:
            dep_id = d.get("id")
            if dep_id:
                lines.append(f"skills/{dep_id}/")
    lines.append("\n# Generated by deps-render")
    lines.append("skills/vendor.manifest.toml")
    lines.append("")
    lines.append(FOOTER)
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: gitignore-render.py <toml_path> <output_path>", file=sys.stderr)
        return 2

    toml_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    with toml_path.open("rb") as f:
        data = tomllib.load(f)

    deps = data.get("deps", []) or []
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render(deps))
    print(f"  ✓ wrote {output_path} ({len(deps)} dep(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
