#!/usr/bin/env python3
"""Interactive onboarding wizard for `ai-specs init` (Rich prompts).

Usage:
  init_tui.py --target <project_root> [--name <prefill>] --out <toml-path>

Exit codes:
  0  user confirmed; wrote TOML to --out
  1  user cancelled (Confirm == No, Ctrl-C, or Ctrl-D/EOF)
  2  usage / argument error
  3  TUI unavailable or unexpected failure (caller falls back to classic init)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tomllib
from pathlib import Path


SUPPORTED_AGENTS = [
    "claude",
    "cursor",
    "opencode",
    "codex",
    "copilot",
    "gemini",
    "pi",
    "omp",
]

DEFAULT_AGENTS = ["claude", "cursor", "opencode"]
DEFAULT_RECIPES = ["session-context"]

# Pin range keeps bootstrap reproducible without chasing every rich major.
RICH_SPEC = "rich>=13.0.0,<15"

_BARE_TOML_KEY = re.compile(r"^[A-Za-z0-9_-]+$")

TOML_HEADER = """\
# ai-specs.toml — project root manifest (generated by ai-specs init --tui).
#
# Canonical surface: [project], [agents], [recipes.<id>], [[deps]],
# [[bindings]], [mcp.<name>], [brief]. See docs/ai-specs-toml.md.
#
# Local skills under ai-specs/skills/<name>/ are autodiscovered.
"""


def _ai_specs_home() -> Path:
    env = os.environ.get("AI_SPECS_HOME")
    if env:
        return Path(env).resolve()
    return Path(__file__).resolve().parents[2]


def _vendor_dir() -> Path:
    return _ai_specs_home() / "lib" / "_vendor"


def _ensure_rich() -> int | None:
    """Make rich importable. Returns exit code 3 if unavailable, else None."""
    vendor = _vendor_dir()
    if vendor.is_dir():
        sys.path.insert(0, str(vendor))

    try:
        import rich  # noqa: F401
        from rich.prompt import Confirm, Prompt  # noqa: F401

        return None
    except ImportError:
        pass

    if not sys.stdin.isatty() or not sys.stdout.isatty():
        return 3

    print("Interactive init needs the 'rich' package.")
    print(f"Install into {_vendor_dir()}? [Y/n] ", end="", flush=True)
    answer = (sys.stdin.readline() or "").strip().lower()
    if answer not in ("", "y", "yes"):
        print("Skipping interactive init.")
        return 3

    try:
        vendor.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"ERROR: cannot create vendor dir {vendor}: {exc}", file=sys.stderr)
        return 3

    cmd = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--quiet",
        "--target",
        str(vendor),
        RICH_SPEC,
    ]
    print("▸ installing rich…")
    try:
        subprocess.run(cmd, check=True)
    except (subprocess.CalledProcessError, OSError) as exc:
        print(f"ERROR: could not install rich: {exc}", file=sys.stderr)
        return 3

    sys.path.insert(0, str(vendor))
    try:
        import rich  # noqa: F401
        from rich.prompt import Confirm, Prompt  # noqa: F401
    except ImportError as exc:
        print(f"ERROR: rich still unavailable after install: {exc}", file=sys.stderr)
        return 3
    return None


def _catalog_recipes() -> list[dict[str, str]]:
    catalog = _ai_specs_home() / "catalog" / "recipes"
    results: list[dict[str, str]] = []
    if not catalog.is_dir():
        return results
    for entry in sorted(catalog.iterdir()):
        if not entry.is_dir() or entry.name.startswith(".") or entry.name.startswith("test-"):
            continue
        recipe_path = entry / "recipe.toml"
        if not recipe_path.is_file():
            continue
        try:
            data = tomllib.loads(recipe_path.read_text(encoding="utf-8"))
            meta = data.get("recipe") or {}
            recipe_id = str(meta.get("id") or entry.name).strip()
            if not recipe_id:
                raise ValueError(f"empty recipe id in {recipe_path}")
            results.append(
                {
                    "id": recipe_id,
                    "name": str(meta.get("name") or entry.name),
                    "version": str(meta.get("version") or "0.0.0"),
                    "description": str(meta.get("description") or ""),
                }
            )
        except Exception as exc:  # noqa: BLE001 — skip unreadable catalog entries
            print(f"  · skip catalog recipe {entry.name}: {exc}", file=sys.stderr)
            continue
    return results


def _load_toml_write():
    import importlib.util

    module_path = Path(__file__).with_name("toml_write.py")
    spec = importlib.util.spec_from_file_location("toml_write", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _toml_key(key: str) -> str:
    """Emit a TOML table key: bare when safe, basic-string quoted otherwise."""
    if _BARE_TOML_KEY.match(key):
        return key
    return json.dumps(key)


def _parse_selection(raw: str, n: int, defaults: list[int]) -> list[int] | None:
    """Parse '1,3' / 'all' / '' (defaults). Returns 0-based indices or None if invalid."""
    text = raw.strip().lower()
    if text == "":
        return list(defaults)
    if text in {"none", "-"}:
        return []
    if text == "all":
        return list(range(n))
    indices: list[int] = []
    for part in text.replace(" ", "").split(","):
        if not part:
            continue
        if not part.isdigit():
            return None
        idx = int(part)
        if idx < 1 or idx > n:
            return None
        indices.append(idx - 1)
    seen: set[int] = set()
    ordered: list[int] = []
    for i in indices:
        if i not in seen:
            seen.add(i)
            ordered.append(i)
    return ordered


def _render_manifest(tw, project_name: str, agents: list[str], recipes: list[dict[str, str]]) -> str:
    lines: list[str] = [
        TOML_HEADER.rstrip(),
        "",
        "[project]",
        f"name = {tw.toml_value(project_name)}",
        "subrepos = []",
        "",
        "[agents]",
        f"enabled = {tw.toml_value(agents)}",
        "",
    ]
    if recipes:
        lines.append("# Recipes — named bundles from catalog/recipes/<id>/")
        for recipe in recipes:
            rid = recipe["id"]
            lines.append(f"[recipes.{_toml_key(rid)}]")
            lines.append("enabled = true")
            lines.append(f"version = {tw.toml_value(recipe.get('version') or '0.0.0')}")
            lines.append("")
    lines.append("# [[deps]] — add with: ai-specs skills add <url>")
    lines.append("# [mcp.*]  — optional MCP servers; distributed by sync-agent")
    lines.append("")
    return "\n".join(lines)


def run_wizard(*, target: Path, name_prefill: str, out_path: Path) -> int:
    err = _ensure_rich()
    if err is not None:
        return err

    # Always require a real TTY for prompts — even when rich is already vendored
    # and the caller forced --tui (EOF would otherwise silently accept defaults).
    if not sys.stdin.isatty() or not sys.stdout.isatty():
        return 3

    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt
    from rich.table import Table

    tw = _load_toml_write()
    console = Console(stderr=True)

    def _cancel() -> int:
        console.print("\n[yellow]Cancelled[/yellow]")
        return 1

    try:
        console.print()
        console.print(
            Panel.fit(
                "[bold]ai-specs init[/bold]\nInteractive project onboarding",
                border_style="cyan",
            )
        )
        console.print(f"  target: [bold]{target}[/bold]")
        console.print()

        default_name = name_prefill or target.name
        project_name = Prompt.ask("Project name", default=default_name).strip() or default_name

        console.print()
        console.print("[bold]Agents[/bold] to enable (fan-out targets for sync-agent)")
        agent_table = Table(show_header=True, header_style="bold")
        agent_table.add_column("#", style="dim", width=3)
        agent_table.add_column("id")
        agent_table.add_column("default")
        default_agent_idxs = [i for i, a in enumerate(SUPPORTED_AGENTS) if a in DEFAULT_AGENTS]
        for i, agent in enumerate(SUPPORTED_AGENTS, start=1):
            agent_table.add_row(str(i), agent, "✓" if agent in DEFAULT_AGENTS else "")
        console.print(agent_table)
        console.print("[dim]Enter numbers (e.g. 1,2,3), 'all', 'none', or blank for defaults[/dim]")

        while True:
            raw = Prompt.ask("Agents", default="")
            picked = _parse_selection(raw, len(SUPPORTED_AGENTS), default_agent_idxs)
            if picked is None:
                console.print("[red]Invalid selection[/red] — try again")
                continue
            agents = [SUPPORTED_AGENTS[i] for i in picked]
            break

        catalog = _catalog_recipes()
        console.print()
        console.print("[bold]Recipes[/bold] to enable from the catalog")
        recipe_table = Table(show_header=True, header_style="bold")
        recipe_table.add_column("#", style="dim", width=3)
        recipe_table.add_column("id", min_width=22)
        recipe_table.add_column("ver", style="dim")
        recipe_table.add_column("description")
        default_recipe_idxs = [i for i, r in enumerate(catalog) if r["id"] in DEFAULT_RECIPES]
        for i, recipe in enumerate(catalog, start=1):
            desc = recipe["description"]
            if len(desc) > 64:
                desc = desc[:61] + "…"
            mark = " ✓" if recipe["id"] in DEFAULT_RECIPES else ""
            recipe_table.add_row(str(i), f"{recipe['id']}{mark}", recipe["version"], desc)
        console.print(recipe_table)
        console.print("[dim]Enter numbers, 'all', 'none', or blank for defaults (session-context)[/dim]")

        while True:
            raw = Prompt.ask("Recipes", default="")
            picked = _parse_selection(raw, len(catalog), default_recipe_idxs)
            if picked is None:
                console.print("[red]Invalid selection[/red] — try again")
                continue
            recipes = [catalog[i] for i in picked]
            break

        console.print()
        console.print(
            Panel.fit(
                f"[bold]name[/bold]     {project_name}\n"
                f"[bold]agents[/bold]   {', '.join(agents) if agents else '(none)'}\n"
                f"[bold]recipes[/bold]  {', '.join(r['id'] for r in recipes) if recipes else '(none)'}\n"
                f"[bold]mcp[/bold]      configure later via ai-specs.toml",
                title="Preview",
                border_style="green",
            )
        )

        if not Confirm.ask("Write ai-specs.toml with these choices?", default=True):
            return _cancel()

        toml_text = _render_manifest(tw, project_name, agents, recipes)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(toml_text, encoding="utf-8")

        meta = {
            "name": project_name,
            "agents": agents,
            "recipes": [r["id"] for r in recipes],
        }
        out_path.with_suffix(".json").write_text(json.dumps(meta) + "\n", encoding="utf-8")
        console.print(f"[green]✓[/green] staged manifest → {out_path}")
        return 0
    except KeyboardInterrupt:
        return _cancel()
    except EOFError:
        return _cancel()


def main() -> int:
    parser = argparse.ArgumentParser(description="ai-specs init interactive onboarding")
    parser.add_argument("--target", required=True, help="Project root path")
    parser.add_argument("--name", default="", help="Prefill project name")
    parser.add_argument("--out", required=True, help="Path to write generated ai-specs.toml")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    if not target.is_dir():
        print(f"ERROR: target is not a directory: {target}", file=sys.stderr)
        return 2

    try:
        return run_wizard(target=target, name_prefill=args.name, out_path=Path(args.out))
    except KeyboardInterrupt:
        # Ctrl-C outside run_wizard's own try (e.g. during _ensure_rich prompt)
        print("\nCancelled", file=sys.stderr)
        return 1
    except EOFError:
        # Ctrl-D / EOF outside run_wizard's own try
        print("\nCancelled", file=sys.stderr)
        return 1
    except Exception as exc:  # noqa: BLE001 — never collide with cancel (rc=1)
        print(f"ERROR: interactive init failed: {exc}", file=sys.stderr)
        return 3


if __name__ == "__main__":
    sys.exit(main())
