#!/usr/bin/env python3
"""Interactive onboarding wizard for `ai-specs init` (Questionary prompts).

Usage:
  init_tui.py --target <project_root> [--name <prefill>] --out <toml-path>

Exit codes:
  0  user confirmed; wrote TOML to --out
  1  user cancelled (Confirm == No, Ctrl-C, or Ctrl-D/EOF)
  2  usage / argument error
  3  TUI unavailable or unexpected failure (caller falls back to classic init)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tomllib
from pathlib import Path


SUPPORTED_AGENTS = [
    "claude",
    "cursor",
    "opencode",
    "codex",
    "copilot",
    "gemini",
    "pi",
    "omp",
]

DEFAULT_AGENTS = ["claude", "cursor", "opencode"]
DEFAULT_RECIPES = ["session-context"]

_BARE_TOML_KEY = re.compile(r"^[A-Za-z0-9_-]+$")

TOML_HEADER = """\
# ai-specs.toml — project root manifest (generated by ai-specs init --tui).
#
# Canonical surface: [project], [agents], [recipes.<id>], [[deps]],
# [[bindings]], [mcp.<name>], [brief]. See docs/ai-specs-toml.md.
#
# Local skills under ai-specs/skills/<name>/ are autodiscovered.
"""


def _load_sibling(name: str):
    """Load a same-directory _internal module by absolute path (sys.path-independent)."""
    import importlib.util

    path = Path(__file__).with_name(f"{name}.py")
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load sibling module {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


_util = _load_sibling("util")


def _ai_specs_home() -> Path:
    return _util.ai_specs_home()


def _vendor_dir() -> Path:
    return _util.vendor_dir()


def _ensure_deps() -> int | None:
    """Make rich + questionary importable. Returns exit code 3 if unavailable, else None."""
    return _util.ensure_deps(_vendor_dir())


def _catalog_recipes() -> list[dict[str, str]]:
    catalog = _ai_specs_home() / "catalog" / "recipes"
    results: list[dict[str, str]] = []
    if not catalog.is_dir():
        return results
    for entry in sorted(catalog.iterdir()):
        if (
            not entry.is_dir()
            or entry.name.startswith(".")
            or _util.is_internal_test_recipe(entry.name)
        ):
            continue
        recipe_path = entry / "recipe.toml"
        if not recipe_path.is_file():
            continue
        try:
            data = tomllib.loads(recipe_path.read_text(encoding="utf-8"))
            meta = data.get("recipe") or {}
            recipe_id = str(meta.get("id") or entry.name).strip()
            if not recipe_id:
                raise ValueError(f"empty recipe id in {recipe_path}")
            results.append(
                {
                    "id": recipe_id,
                    "name": str(meta.get("name") or entry.name),
                    "version": str(meta.get("version") or "0.0.0"),
                    "description": str(meta.get("description") or ""),
                }
            )
        except Exception as exc:  # noqa: BLE001 — skip unreadable catalog entries
            print(f"  · skip catalog recipe {entry.name}: {exc}", file=sys.stderr)
            continue
    return results


def _load_toml_write():
    import importlib.util

    module_path = Path(__file__).with_name("toml_write.py")
    spec = importlib.util.spec_from_file_location("toml_write", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _toml_key(key: str) -> str:
    """Emit a TOML table key: bare when safe, basic-string quoted otherwise."""
    if _BARE_TOML_KEY.match(key):
        return key
    return json.dumps(key)




def _render_manifest(
    tw,
    project_name: str,
    agents: list[str],
    recipes: list[dict[str, str]],
    configured: dict | None = None,
) -> str:
    lines: list[str] = [
        TOML_HEADER.rstrip(),
        "",
        "[project]",
        f"name = {tw.toml_value(project_name)}",
        "subrepos = []",
        "",
        "[agents]",
        f"enabled = {tw.toml_value(agents)}",
        "",
    ]
    configured = configured or {}
    if recipes:
        lines.append("# Recipes — named bundles from catalog/recipes/<id>/")
        for recipe in recipes:
            rid = recipe["id"]
            lines.append(f"[recipes.{_toml_key(rid)}]")
            lines.append("enabled = true")
            vals = configured.get(rid) or {}
            if vals:
                lines.append("")
                lines.append(f"[recipes.{_toml_key(rid)}.config]")
                for key in sorted(vals):
                    lines.append(f"{_toml_key(key)} = {tw.toml_value(vals[key])}")
            lines.append("")
    lines.append("# [[deps]] — add with: ai-specs skills add <url>")
    lines.append("# [mcp.*]  — optional MCP servers; distributed by sync-agent")
    lines.append("")
    return "\n".join(lines)


def _configure_recipes(recipes: list[dict[str, str]], console, catalog_dir: Path) -> dict:
    """Step 3.5 — optional per-recipe config + dep panel. Returns configured map."""
    import questionary

    wizard = _load_sibling("config_wizard")
    recipe_read = _load_sibling("recipe-read")
    configured: dict = {}
    for meta in recipes:
        rid = meta["id"]
        try:
            recipe = recipe_read.read_recipe(catalog_dir, rid)
        except Exception as exc:  # noqa: BLE001
            console.print(f"[yellow]skip config for {rid}: {exc}[/yellow]")
            continue
        if recipe.cli_deps and not wizard._dep_gate(recipe, console):
            console.print(f"[yellow]Skipped {rid} (missing CLI deps)[/yellow]")
            continue
        if not recipe.config_schema.fields:
            continue
        do_now = questionary.confirm(f"Configure {rid} now?", default=True).ask()
        if do_now is None:
            raise KeyboardInterrupt
        if not do_now:
            continue
        values = wizard.run_config_wizard(recipe, {})
        if values:
            configured[rid] = values
    return configured


def run_wizard(*, target: Path, name_prefill: str, out_path: Path) -> int:
    err = _ensure_deps()
    if err is not None:
        return err

    # Always require a real TTY for prompts — even when deps are already vendored
    # and the caller forced --tui (EOF would otherwise silently accept defaults).
    if not sys.stdin.isatty() or not sys.stdout.isatty():
        return 3

    import questionary
    from rich.console import Console
    from rich.panel import Panel

    tw = _load_toml_write()
    console = Console(stderr=True)

    def _cancel() -> int:
        console.print("\n[yellow]Cancelled[/yellow]")
        return 1

    try:
        console.print()
        console.print(
            Panel.fit(
                "[bold]ai-specs init[/bold]\nInteractive project onboarding",
                border_style="cyan",
            )
        )
        console.print(f"  target: [bold]{target}[/bold]")
        console.print()

        # 1. Project name — text input with default
        default_name = name_prefill or target.name
        project_name = questionary.text("Project name:", default=default_name).ask()
        if project_name is None:
            return _cancel()
        project_name = project_name.strip() or default_name

        # 1b. Repo topology — confirm auto-detect (worktree-flow)
        det = _util.resolve_repo_topology(target, "auto")
        topo_choices = [
            questionary.Choice(
                title=f"auto → {det.resolved} (detected)",
                value="auto",
            ),
            questionary.Choice(title="standalone", value="standalone"),
            questionary.Choice(title="monorepo-apps", value="monorepo-apps"),
            questionary.Choice(title="monorepo-submodules", value="monorepo-submodules"),
        ]
        topology = questionary.select(
            "Repo topology for worktree-flow:",
            choices=topo_choices,
            default=topo_choices[0],
        ).ask()
        if topology is None:
            return _cancel()

        # 2. Agents — checkbox multi-select with arrow keys + space toggle
        console.print()
        agent_choices = [
            questionary.Choice(
                title=agent,
                value=agent,
                checked=agent in DEFAULT_AGENTS,
            )
            for agent in SUPPORTED_AGENTS
        ]
        agents = questionary.checkbox(
            "Select agents to enable:",
            choices=agent_choices,
        ).ask()
        if agents is None:
            return _cancel()

        # 3. Recipes — checkbox multi-select from catalog
        catalog = _catalog_recipes()
        if catalog:
            recipe_choices = [
                questionary.Choice(
                    title=f"{r['id']}  ({r['version']}) — {r['description'][:64]}",
                    value=r,
                    checked=r["id"] in DEFAULT_RECIPES,
                )
                for r in catalog
            ]
            recipes = questionary.checkbox(
                "Select recipes to enable:",
                choices=recipe_choices,
            ).ask()
            if recipes is None:
                return _cancel()
        else:
            recipes = []

        # 3.5 Configure selected recipes (optional per-recipe)
        catalog_dir = _ai_specs_home() / "catalog" / "recipes"
        configured = _configure_recipes(recipes, console, catalog_dir) if recipes else {}
        # Identity topology is a convenience default only. A later explicit
        # answer from _configure_recipes (schema-driven enum) wins — do not
        # clobber repo_topology if already set.
        if any(r.get("id") == "worktree-flow" for r in recipes):
            configured.setdefault("worktree-flow", {}).setdefault(
                "repo_topology", topology
            )

        # 4. Preview + confirm
        console.print()
        config_summary = (
            ", ".join(sorted(configured)) if configured else "(defaults / later)"
        )
        console.print(
            Panel.fit(
                f"[bold]name[/bold]     {project_name}\n"
                f"[bold]agents[/bold]   {', '.join(agents) if agents else '(none)'}\n"
                f"[bold]recipes[/bold]  {', '.join(r['id'] for r in recipes) if recipes else '(none)'}\n"
                f"[bold]config[/bold]   {config_summary}\n"
                f"[bold]mcp[/bold]      configure later via ai-specs.toml",
                title="Preview",
                border_style="green",
            )
        )

        confirmed = questionary.confirm(
            "Write ai-specs.toml with these choices?",
            default=True,
        ).ask()
        if not confirmed:
            return _cancel()

        toml_text = _render_manifest(tw, project_name, agents, recipes, configured)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(toml_text, encoding="utf-8")

        # Fresh init stages --out; init.sh copies after TUI exits. Place the
        # confirmed manifest at the real path now so harness-env collection can
        # see enabled recipes (never overwrite an existing project toml).
        real_toml = target / "ai-specs" / "ai-specs.toml"
        if not real_toml.is_file():
            real_toml.parent.mkdir(parents=True, exist_ok=True)
            real_toml.write_text(toml_text, encoding="utf-8")

        meta = {
            "name": project_name,
            "agents": agents,
            "recipes": [r["id"] for r in recipes],
            "configured": sorted(configured),
        }
        out_path.with_suffix(".json").write_text(json.dumps(meta) + "\n", encoding="utf-8")
        console.print(f"[green]✓[/green] staged manifest → {out_path}")

        # Prompt for MCP env vars → ai-specs.env + root .envrc + direnv allow.
        try:
            env = _load_sibling("env_scaffold")
            if env.collect_env_vars(target):
                env.offer_harness_env(target)
        except Exception:
            pass
        return 0
    except KeyboardInterrupt:
        return _cancel()
    except EOFError:
        return _cancel()


def main() -> int:
    parser = argparse.ArgumentParser(description="ai-specs init interactive onboarding")
    parser.add_argument("--target", required=True, help="Project root path")
    parser.add_argument("--name", default="", help="Prefill project name")
    parser.add_argument("--out", required=True, help="Path to write generated ai-specs.toml")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    if not target.is_dir():
        print(f"ERROR: target is not a directory: {target}", file=sys.stderr)
        return 2

    try:
        return run_wizard(target=target, name_prefill=args.name, out_path=Path(args.out))
    except KeyboardInterrupt:
        # Ctrl-C outside run_wizard's own try (e.g. during _ensure_deps install prompt)
        print("\nCancelled", file=sys.stderr)
        return 1
    except EOFError:
        # Ctrl-D / EOF outside run_wizard's own try
        print("\nCancelled", file=sys.stderr)
        return 1
    except Exception as exc:  # noqa: BLE001 — never collide with cancel (rc=1)
        print(f"ERROR: interactive init failed: {exc}", file=sys.stderr)
        return 3


if __name__ == "__main__":
    sys.exit(main())
