#!/usr/bin/env python3
"""Generate ai-specs/.skill-registry.md from resolved skills.

Usage:
  registry-render.py <project_root> [--dry-run] [--scope <scope>]
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any

import skill_contract


def _load_skill_resolution() -> Any:
    module_path = Path(__file__).with_name("skill-resolution.py")
    spec = importlib.util.spec_from_file_location("skill_resolution_internal", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load skill-resolution.py at {module_path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    args = sys.argv[1:]
    if not args:
        print(f"Usage: {sys.argv[0]} <project_root> [--dry-run] [--scope <scope>]", file=sys.stderr)
        return 2

    project_root = Path(args[0]).resolve()
    dry_run = False
    filter_scope = ""

    i = 1
    while i < len(args):
        if args[i] == "--dry-run":
            dry_run = True
            i += 1
        elif args[i] == "--scope" and i + 1 < len(args):
            filter_scope = args[i + 1]
            i += 2
        else:
            print(f"Unknown argument: {args[i]}", file=sys.stderr)
            return 2

    manifest_path = project_root / "ai-specs" / "ai-specs.toml"
    if not manifest_path.is_file():
        print(f"Skipping registry generation — no manifest found at {manifest_path}")
        return 0

    skill_resolution = _load_skill_resolution()
    resolved = skill_resolution.collect_skills(project_root)
    skill_ids = sorted(resolved.keys())

    index_rows: list[tuple[str, str, str, str]] = []
    auto_invoke_rows: list[tuple[str, str, str]] = []
    errors: list[str] = []

    for skill_id in skill_ids:
        source_type, abs_path = resolved[skill_id]
        skill_md = abs_path / "SKILL.md"
        if not skill_md.is_file():
            continue

        try:
            skill = skill_contract.from_local_skill(skill_md, compatibility=True)
        except Exception as exc:
            errors.append(f"{skill_md}: {exc}")
            continue

        # Skill Index row
        try:
            rel_path = skill_md.relative_to(project_root)
        except ValueError:
            rel_path = skill_md
        desc = skill["description_summary"].replace("|", "\\|")
        index_rows.append((skill_id, source_type, desc, str(rel_path)))

        # Auto-invoke validation and rows
        try:
            sync_meta = skill_contract.validate_sync_metadata(skill, path=skill_md)
        except skill_contract.SkillContractError as exc:
            meta = skill.get("metadata") or {}
            if meta.get("scope") or meta.get("auto_invoke"):
                errors.append(str(exc))
            continue

        if sync_meta["enabled"]:
            for scope in sorted(sync_meta["scope"]):
                if filter_scope and scope != filter_scope:
                    continue
                for action in sorted(sync_meta["auto_invoke"]):
                    auto_invoke_rows.append((action, skill_id, scope))

    if errors:
        for err in errors:
            print(f"ERROR: {err}", file=sys.stderr)
        return 1

    lines = [
        "> **Auto-generated by `ai-specs sync`. Do not edit by hand.**",
        "",
        "## Skill Index",
        "",
        "| Skill | Source | Description | Path |",
        "|-------|--------|-------------|------|",
    ]
    for skill_id, source_type, desc, path in index_rows:
        lines.append(f"| `{skill_id}` | {source_type} | {desc} | [{path}]({path}) |")
    lines.append("")

    lines.append("## Auto-invoke Mappings")
    lines.append("")
    if auto_invoke_rows:
        lines.append("| Action | Skill | Scope |")
        lines.append("|--------|-------|-------|")
        for action, skill_id, scope in auto_invoke_rows:
            lines.append(f"| {action} | `{skill_id}` | `{scope}` |")
        lines.append("")
    else:
        lines.append("_No auto-invoke mappings._")
        lines.append("")

    text = "\n".join(lines).rstrip() + "\n"

    registry_path = project_root / "ai-specs" / ".skill-registry.md"
    if dry_run:
        print(text)
    else:
        registry_path.parent.mkdir(parents=True, exist_ok=True)
        registry_path.write_text(text)
        print(f"  ✓ wrote {registry_path} ({len(index_rows)} skill(s), {len(auto_invoke_rows)} auto-invoke row(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
